import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { getPreset, type Preset } from "@harnesstrim/core";

export const OPENCODE_PLUGIN_NAME = "@harnesstrim/adapter-opencode";
/** Published, self-contained (no runtime deps) — resolvable by a local wrapper import. */
export const OPENCODE_ADAPTER_VERSION = "^0.0.2";

/**
 * Default options baked into the generated wrapper. Telemetry is ON here (unlike the
 * library default) because `install` is an explicit opt-in and the metrics file is the
 * only practical signal that reduction is happening inside OpenCode Desktop.
 */
export const DEFAULT_OPENCODE_ADAPTER_CONFIG: Record<string, unknown> = {
  mode: "active",
  telemetry: true,
  telemetryPath: ".harnesstrim/metrics.jsonl",
};

// Files, relative to the project dir.
const WRAPPER_REL = path.join(".opencode", "plugin", "harnesstrim.ts");
const PKG_REL = path.join(".opencode", "package.json");
const OPENCODE_JSON = "opencode.json";

/**
 * Build the local plugin wrapper. OpenCode's `plugin` config is a plain string array and
 * does NOT pass options to plugins (confirmed against the OpenCode docs), so per-plugin
 * config (mode / telemetry / minLength / preset) can only be applied through a local
 * plugin file auto-loaded from `.opencode/plugin/`. This wrapper imports the published,
 * self-contained adapter and calls it with the resolved options.
 */
export function buildOpencodeWrapper(adapterConfig: Record<string, unknown>): string {
  const opts = JSON.stringify(adapterConfig, null, 2).replace(/\n/g, "\n  ");
  return `// Generated by \`harnesstrim install opencode\`. Do not reference this plugin from
// opencode.json — OpenCode's \`plugin\` field is a string array and cannot pass options,
// so HarnessTrim options live here and OpenCode auto-loads this file from .opencode/plugin/.
// The dependency is declared in ../package.json. Edit the options below freely.
import { HarnessTrim } from "${OPENCODE_PLUGIN_NAME}";

export const HarnessTrimPlugin = async (input) =>
  HarnessTrim(input, ${opts});
`;
}

/** Merge our dependency into an existing (or new) .opencode/package.json, sorted, 2-space. */
export function buildOpencodePackageJson(existing: string | null): string {
  let base: Record<string, unknown> = {};
  if (existing) {
    try {
      const parsed = JSON.parse(existing);
      if (parsed && typeof parsed === "object") base = parsed as Record<string, unknown>;
    } catch {
      /* overwrite unparseable package.json */
    }
  }
  const deps: Record<string, unknown> = { ...(base.dependencies as Record<string, unknown> | undefined) };
  deps[OPENCODE_PLUGIN_NAME] = OPENCODE_ADAPTER_VERSION;
  return JSON.stringify({ ...base, dependencies: deps }, null, 2) + "\n";
}

/** True if the parsed opencode.json plugin array references our adapter (string/tuple/legacy). */
function opencodeJsonReferencesAdapter(config: Record<string, unknown>): boolean {
  const plugin = config.plugin;
  if (!Array.isArray(plugin)) return false;
  return plugin.some((e) => {
    if (typeof e === "string") return e.includes(OPENCODE_PLUGIN_NAME);
    if (Array.isArray(e)) return typeof e[0] === "string" && e[0].includes(OPENCODE_PLUGIN_NAME);
    if (e && typeof e === "object") {
      const name = (e as Record<string, unknown>).name;
      return typeof name === "string" && name.includes(OPENCODE_PLUGIN_NAME);
    }
    return false;
  });
}

/**
 * Remove our adapter from an opencode.json `plugin` array (it belongs in the wrapper now,
 * not here). Returns the cleaned config, or null when there is nothing to change.
 */
function cleanOpencodeJson(existing: string): { content: string } | null {
  let config: Record<string, unknown>;
  try {
    config = JSON.parse(existing) as Record<string, unknown>;
  } catch {
    throw new Error(`${OPENCODE_JSON} exists but is not valid JSON`);
  }
  if (!opencodeJsonReferencesAdapter(config)) return null;
  const plugin = (config.plugin as unknown[]).filter((e) => {
    if (typeof e === "string") return !e.includes(OPENCODE_PLUGIN_NAME);
    if (Array.isArray(e)) return !(typeof e[0] === "string" && e[0].includes(OPENCODE_PLUGIN_NAME));
    if (e && typeof e === "object") {
      const name = (e as Record<string, unknown>).name;
      return !(typeof name === "string" && name.includes(OPENCODE_PLUGIN_NAME));
    }
    return true;
  });
  const next: Record<string, unknown> = { ...config };
  if (plugin.length === 0) delete next.plugin;
  else next.plugin = plugin;
  return { content: JSON.stringify(next, null, 2) + "\n" };
}

export interface OpencodeInstallPlan {
  wrapperContent: string;
  packageJsonContent: string;
  /** Cleaned opencode.json content, or null when opencode.json needs no change. */
  opencodeJsonContent: string | null;
  alreadyInstalled: boolean;
  changed: boolean;
}

/**
 * Pure planner: given the existing files (or null) and the resolved adapter config,
 * compute the desired wrapper + package.json + opencode.json cleanup and whether
 * anything changes. Idempotent: re-running with identical inputs yields changed=false.
 */
export function planOpencodeInstall(input: {
  existingWrapper: string | null;
  existingPackageJson: string | null;
  existingOpencodeJson: string | null;
  adapterConfig?: Record<string, unknown>;
}): OpencodeInstallPlan {
  const adapterConfig = input.adapterConfig ?? DEFAULT_OPENCODE_ADAPTER_CONFIG;
  const wrapperContent = buildOpencodeWrapper(adapterConfig);
  const packageJsonContent = buildOpencodePackageJson(input.existingPackageJson);

  const opencodeClean = input.existingOpencodeJson ? cleanOpencodeJson(input.existingOpencodeJson) : null;
  const opencodeJsonContent = opencodeClean?.content ?? null;

  const wrapperChanged = input.existingWrapper !== wrapperContent;
  const pkgChanged = input.existingPackageJson !== packageJsonContent;
  const opencodeChanged = opencodeJsonContent !== null;

  const alreadyInstalled = input.existingWrapper !== null;
  const changed = wrapperChanged || pkgChanged || opencodeChanged;

  return { wrapperContent, packageJsonContent, opencodeJsonContent, alreadyInstalled, changed };
}

export interface InstallResult extends OpencodeInstallPlan {
  wrapperPath: string;
  packageJsonPath: string;
  opencodeJsonPath: string;
  existed: boolean;
  applied: boolean;
  /** Whether the `.opencode` dependency install ran and succeeded (null = not attempted). */
  depsInstalled: boolean | null;
  depsMessage?: string;
  preset?: Preset;
}

/**
 * Compute (and optionally apply) the OpenCode install. Dry-run by default. Generates the
 * local wrapper + `.opencode/package.json`, cleans any adapter reference out of
 * opencode.json, and (on --apply) installs the `.opencode` dependency so the wrapper
 * resolves. A preset's adapter config is baked into the wrapper options.
 */
export function runInstallOpencode(
  dir: string,
  apply: boolean,
  presetName?: string,
  installDeps = true,
): InstallResult {
  let preset: Preset | undefined;
  let adapterConfig = { ...DEFAULT_OPENCODE_ADAPTER_CONFIG };
  if (presetName) {
    preset = getPreset(presetName);
    if (!preset) throw new Error(`Unknown preset: ${presetName}`);
    adapterConfig = { ...adapterConfig, ...preset.adapter };
  }

  const wrapperPath = path.join(dir, WRAPPER_REL);
  const packageJsonPath = path.join(dir, PKG_REL);
  const opencodeJsonPath = path.join(dir, OPENCODE_JSON);

  const readOrNull = (p: string): string | null => {
    try {
      return fs.readFileSync(p, "utf8");
    } catch {
      return null;
    }
  };

  const existingWrapper = readOrNull(wrapperPath);
  const existingPackageJson = readOrNull(packageJsonPath);
  const existingOpencodeJson = readOrNull(opencodeJsonPath);

  const plan = planOpencodeInstall({
    existingWrapper,
    existingPackageJson,
    existingOpencodeJson,
    adapterConfig,
  });

  let applied = false;
  let depsInstalled: boolean | null = null;
  let depsMessage: string | undefined;

  if (apply && plan.changed) {
    fs.mkdirSync(path.dirname(wrapperPath), { recursive: true });
    fs.writeFileSync(wrapperPath, plan.wrapperContent);
    fs.writeFileSync(packageJsonPath, plan.packageJsonContent);
    if (plan.opencodeJsonContent !== null) fs.writeFileSync(opencodeJsonPath, plan.opencodeJsonContent);
    applied = true;

    // Install the wrapper's dependency so the import resolves. Best-effort: a failure here
    // (offline, no npm) must not fail the install — the user can install .opencode manually.
    if (installDeps) {
      const npm = process.platform === "win32" ? "npm.cmd" : "npm";
      const res = spawnSync(npm, ["install", "--silent"], {
        cwd: path.dirname(packageJsonPath),
        encoding: "utf8",
      });
      if (res.error || res.status !== 0) {
        depsInstalled = false;
        depsMessage = `Could not auto-install the adapter; run \`npm install\` in ${path.dirname(packageJsonPath)}.`;
      } else {
        depsInstalled = true;
      }
    }
  }

  return {
    ...plan,
    wrapperPath,
    packageJsonPath,
    opencodeJsonPath,
    existed: existingWrapper !== null,
    applied,
    depsInstalled,
    depsMessage,
    preset,
  };
}
