import type { Reducer, ReducerResult } from "./types.ts";

const MARKER_PREFIX = "[harnesstrim:cron-output-slim]";
const CRON_HEADER_RE = /^# Cron Job:/m;
const PROMPT_RE = /^## Prompt\s*$/m;
const RESPONSE_RE = /^## Response\s*$/m;

/**
 * Cron output generated by Hermes includes the full submitted prompt and loaded
 * skills before the actual response. The prompt is already durable in the cron
 * archive and repeating it in a tool result wastes context. Keep the job header
 * and final response, replacing only that archival prompt section with a marker.
 */
export const cronOutputSlim: Reducer = {
  name: "cron-output-slim",
  reduce(input: string): ReducerResult {
    if (input.includes(MARKER_PREFIX) || !CRON_HEADER_RE.test(input)) {
      return { output: input, changed: false };
    }

    const prompt = PROMPT_RE.exec(input);
    const response = RESPONSE_RE.exec(input);
    if (!prompt || !response || response.index <= prompt.index) {
      return { output: input, changed: false };
    }

    const promptEnd = input.indexOf("\n", prompt.index) + 1;
    const omitted = input.slice(promptEnd, response.index);
    const omittedLines = omitted.split(/\r?\n/).filter(Boolean).length;
    if (omittedLines === 0) return { output: input, changed: false };

    const output = `${input.slice(0, promptEnd)}${MARKER_PREFIX} omitted ${omittedLines} archived prompt/skill line(s)\n\n${input.slice(response.index)}`;
    return {
      output,
      changed: true,
      note: `omitted ${omittedLines} archived prompt/skill line(s)`,
    };
  },
};
